parameters:

services:
    wk_base.abstract:
        class: Wk\BaseBundle\Services\PersistenceService
        abstract: true
        arguments: ['@doctrine_mongodb.odm.document_manager']
        calls:
            - [setLogger, ["@logger"]]
